#version 460 core

// Local group size
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Bindings
layout(set = 0, binding = 0, std430) buffer ColorBuffer
{
	vec4 data[];
} color_buffer;

void main()
{
	uint idx = gl_GlobalInvocationID.x;
	uint idy = gl_GlobalInvocationID.y;
	uint width = gl_NumWorkGroups.x;
	uint height = gl_NumWorkGroups.y;

	// Set color to buffer
	color_buffer.data[idx + idy * width].rgba = vec4(1, 1, 1, 1);
}
