#version 460 core

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Structs
struct Sphere
{
	vec4 pos;
	float radius;
	int color;
};

// Bindings
layout(set = 0, binding = 0, std430) buffer ColorBuffer
{
	uint data[];
} color_buffer;

void main()
{
	uint idx = gl_GlobalInvocationID.x;
	uint width = gl_NumWorkGroups.x;
	uint height = gl_NumWorkGroups.y;

	color_buffer.data[idx] = idx;
}
